# Generated by Django 3.0.8 on 2020-08-04 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todoitem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
