# Generated by Django 3.0.8 on 2020-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_urgentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='detail',
            field=models.TextField(default='This is empty'),
            preserve_default=False,
        ),
    ]
